# Generated by Django 5.0.1 on 2024-03-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='email',
        ),
    ]
